# Generated by scripts/update-formula.py when a release is published.
class Paddock < Formula
  desc "Every dev server on this machine, in one place"
  homepage "https://github.com/musaJawad004/paddock"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/musaJawad004/paddock/releases/download/v0.2.0/paddock-aarch64-apple-darwin.tar.gz"
      sha256 "dee328ec35d6ddebfc54bd66201d11cd168645913b638481d2cac9987be6f151"
    end
    on_intel do
      url "https://github.com/musaJawad004/paddock/releases/download/v0.2.0/paddock-x86_64-apple-darwin.tar.gz"
      sha256 "e8a602b74b28c964ceac9109e818abdd9141ef7f530735963ef747517bdc6b92"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/musaJawad004/paddock/releases/download/v0.2.0/paddock-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "86df8a1bfee1fb1e527df5666e41df8600ef22d43fa994cf945bff3823a09b84"
    end
    on_intel do
      url "https://github.com/musaJawad004/paddock/releases/download/v0.2.0/paddock-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d35c61853545769f1fb401e3c5357c0bca68b9ed00f960cca2e60085013c5250"
    end
  end

  def install
    bin.install "paddock"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/paddock --version")
  end
end
