# Generated by scripts/update-formula.py when a release is published.
class Paddock < Formula
  desc "Every dev server on this machine, in one place"
  homepage "https://github.com/musaJawad004/paddock"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/musaJawad004/paddock/releases/download/v0.1.0/paddock-aarch64-apple-darwin.tar.gz"
      sha256 "befc146f624b982664f933595b3aa75f7b32a8e1d7247bec84d07c4a4db90260"
    end
    on_intel do
      url "https://github.com/musaJawad004/paddock/releases/download/v0.1.0/paddock-x86_64-apple-darwin.tar.gz"
      sha256 "38ed38fed680891f1d156181991a9fe7373da944fe210c949a3b9eef1d9145a0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/musaJawad004/paddock/releases/download/v0.1.0/paddock-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "36297450ce338c9ed7459ad43bda29013e058336765675b34f3e6d4c0ac9fa33"
    end
    on_intel do
      url "https://github.com/musaJawad004/paddock/releases/download/v0.1.0/paddock-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6f15b39ea4db83cd140e6c1f59d179b6be7dfb690e34f57db92774ced8a9876a"
    end
  end

  def install
    bin.install "paddock"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/paddock --version")
  end
end
