#!/usr/bin/env python3
"""Print the Homebrew formula for a release.

    scripts/update-formula.py 0.1.0 dist > Formula/paddock.rb

`dist` holds the release archives and their .sha256 files, as the release
workflow downloads them.
"""

import pathlib
import sys

REPO = "https://github.com/musaJawad004/paddock"

TARGETS = {
    "mac_arm": "aarch64-apple-darwin",
    "mac_intel": "x86_64-apple-darwin",
    "linux_arm": "aarch64-unknown-linux-gnu",
    "linux_intel": "x86_64-unknown-linux-gnu",
}


def sha(dist, target):
    path = dist / f"paddock-{target}.tar.gz.sha256"
    return path.read_text().split()[0]


def main():
    version, dist = sys.argv[1], pathlib.Path(sys.argv[2])
    url = lambda target: f"{REPO}/releases/download/v{version}/paddock-{target}.tar.gz"
    block = lambda key: (
        f'      url "{url(TARGETS[key])}"\n'
        f'      sha256 "{sha(dist, TARGETS[key])}"\n'
    )
    print(f'''# Generated by scripts/update-formula.py when a release is published.
class Paddock < Formula
  desc "Every dev server on this machine, in one place"
  homepage "{REPO}"
  version "{version}"
  license "MIT"

  on_macos do
    on_arm do
{block("mac_arm")}    end
    on_intel do
{block("mac_intel")}    end
  end

  on_linux do
    on_arm do
{block("linux_arm")}    end
    on_intel do
{block("linux_intel")}    end
  end

  def install
    bin.install "paddock"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/paddock --version")
  end
end''')


if __name__ == "__main__":
    main()
